# Generated by Django 5.2.17 on 2026-08-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. +67%, 19, $1B', max_length=40)),
                ('label', models.CharField(help_text='e.g. YoY revenue', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Portfolio', max_length=120)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('subheadline', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('available', models.BooleanField(default=True)),
                ('availability_text', models.CharField(blank=True, default='Available for new projects', max_length=120)),
                ('booking_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('footer_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('process', 'Process'), ('pricing', 'Pricing'), ('about', 'About'), ('ask', 'Ask')], max_length=40)),
                ('section_key', models.SlugField(help_text="Must match the key the template looks up, e.g. 'hero', 'credibility', 'how-i-help'.", max_length=80)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_content/')),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Page content block',
                'ordering': ['page', 'section_key'],
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
