# Generated by Django 5.2.17 on 2026-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="e.g. '01'", max_length=10)),
                ('week_label', models.CharField(blank=True, help_text="e.g. 'Week 1-2'", max_length=60)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('ai_in_action', models.TextField(blank=True, help_text='How AI is used during this phase.')),
                ('what_you_get', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
