# Generated by Django 5.2.17 on 2026-08-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV / Resume (PDF)'),
        ),
    ]
