# Generated by Django 5.2.17 on 2026-08-27 21:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_content/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/', validators=[core.validators.MaxFileSizeValidator(10), core.validators.validate_pdf_content], verbose_name='CV / Resume (PDF)'),
        ),
    ]
