# Generated by Django 5.2.17 on 2026-08-28 21:28

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pagecontent_image_alter_sitesettings_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.get_raw_storage, upload_to='cv/', validators=[core.validators.MaxFileSizeValidator(10), core.validators.validate_pdf_content], verbose_name='CV / Resume (PDF)'),
        ),
    ]
