# Generated by Django 5.2.17 on 2026-08-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('duration', models.CharField(blank=True, help_text="e.g. '4-6 weeks'", max_length=80)),
                ('badge', models.CharField(blank=True, help_text="e.g. 'MOST POPULAR'", max_length=60)),
                ('availability_text', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('cta_label', models.CharField(default='Learn more', max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
