# Generated by Django 5.2.17 on 2026-08-27 21:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
    ]
