# Generated by Django 5.2.17 on 2026-08-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('challenge', models.TextField(blank=True)),
                ('strategy', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('primary_metric', models.CharField(blank=True, help_text="e.g. '+67% YoY revenue'", max_length=80)),
                ('secondary_metric', models.CharField(blank=True, max_length=80)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='case_studies/hero/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='case_studies/thumbnails/')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order'],
            },
        ),
    ]
