# Generated by Django 5.2.17 on 2026-08-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_casestudysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='live_url',
            field=models.URLField(blank=True, help_text="Link to the live site, if it's still online."),
        ),
    ]
