# Generated by Django 5.2.17 on 2026-08-27 21:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_casestudy_live_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/hero/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/thumbnails/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='casestudysection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/sections/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
    ]
