# Generated by Django 5.2.17 on 2026-08-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='skills_highlight',
            field=models.TextField(blank=True, help_text='Key skills or knowledge gained — one per line. Shown on the card for SEO and page richness.'),
        ),
    ]
