# Generated by Django 5.2.17 on 2026-08-27 21:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_certification_skills_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
    ]
