# Generated by Django 5.2.17 on 2026-08-27 21:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_case_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/avatars/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='videotestimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/video_thumbs/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
    ]
