# Generated by Django 5.2.17 on 2026-08-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('audiobook', 'Audiobook'), ('training', 'Training')], max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resources/covers/')),
                ('preview_url', models.URLField(blank=True, help_text='Link to a sample or preview — excerpt, trailer, free lesson, etc.')),
                ('sample_file', models.FileField(blank=True, help_text='Downloadable preview file (sample chapter, audio snippet, syllabus...).', null=True, upload_to='resources/samples/')),
                ('purchase_url', models.URLField(blank=True, help_text='Where visitors buy or access this (Gumroad, Selar, WhatsApp, etc.).')),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
