# Generated by Django 5.2.17 on 2026-08-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('book', 'Livre'), ('audiobook', 'Livre audio'), ('training', 'Formation')], max_length=20),
        ),
    ]
