# Generated by Django 5.2.17 on 2026-08-27 21:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/covers/', validators=[core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sample_file',
            field=models.FileField(blank=True, help_text='Downloadable preview file (sample chapter, audio snippet, syllabus...).', null=True, upload_to='resources/samples/', validators=[core.validators.MaxFileSizeValidator(25), core.validators.validate_safe_extension]),
        ),
    ]
