# Generated by Django 5.2.17 on 2026-08-28 21:28

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='sample_file',
            field=models.FileField(blank=True, help_text='Downloadable preview file (sample chapter, audio snippet, syllabus...).', null=True, storage=core.storage.get_raw_storage, upload_to='resources/samples/', validators=[core.validators.MaxFileSizeValidator(25), core.validators.validate_safe_extension]),
        ),
    ]
